### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by frese** [chemoish/atom-valign#6]
Using the below lines (puppet script)

  $prefix = hiera('net::dns::vpngw::default')
  $env = hiera('net::dns::environment')
  $topdomain = hiera('net::dns::topdomain')

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [valign](https://github.com/chemoish/atom-valign) package, v0.13.4

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Users/af/.atom/packages/valign/lib/valign-formatter.coffee:2

RangeError: Invalid array length
  at getSpaces (/Users/af/.atom/packages/valign/lib/valign-formatter.coffee:2:10)
  at Object.module.exports.buildText (/Users/af/.atom/packages/valign/lib/valign-formatter.coffee:55:21)
  at Object.module.exports.formatBlock (/Users/af/.atom/packages/valign/lib/valign-formatter.coffee:150:13)
  at Object.module.exports.align (/Users/af/.atom/packages/valign/lib/valign.coffee:12:21)
  at atom-text-editor.atom.commands.add.valign:align (/Users/af/.atom/packages/valign/lib/valign.coffee:6:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:12.3 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  7x -0:12.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:11.5 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:11.1 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:10.8 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:10.3 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:10.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.5 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.2 core:close (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.2 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.2 core:close (div.settings-view.pane-item)
     -0:05.1 blur (div.settings-view.pane-item)
     -0:03.7 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.1 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.2 valign:align (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "linter-shellcheck",
      "project-manager",
      "linter-clang",
      "linter-javac",
      "linter-tidy",
      "tabularize",
      "vertical-align"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.9.1
atom-beautify, v0.23.0
autocomplete-plus, v2.6.0
git-control, v0.1.8
git-projects, v1.11.1
language-puppet, v0.10.0
linter, v0.12.0
linter-puppet-lint, v0.2.8
linter-pylint, v0.2.1
linter-ruby, v0.1.4
valign, v0.13.4
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by chemoish** [comment]
Hi @frese,

I currently don't have a Mac to debug this. On Windows, in an Null Grammar file (Which shouldn't matter). It works for me.

Obviously, the `getSpaces()` is being returned an invalid sized array (Probably -1).

Could you either help me debug it? Or could provide me with additional steps so I can try and replicate?

**Comment by chemoish** [comment]
@frese, I refactored the entire package. There are breaking changes, but let me know if this solves your immediate issue.

**Comment by frese** [comment]
It sure did :-)   -  Thanks a lot for a great tool !!
